### ISSUE TITLE
Provide other formats for time ranges

### ISSUE THREAD

**Issue by retzkek** [fifemon/graphql-datasource#10]
Different APIs will expect different time formats, so we need to provide a way to specify the format for `$timeFrom` and `$timeTo`. At a minimum there should be a way to get ISO8601 formatted strings. I'm not sure if we need or want to go as far as supporting arbitrary format strings.

Maybe just add `$time{From|To}ISO` for now?

**Comment by retzkek** [comment]
If we were going to support more or arbitrary formats, maybe we should follow the convention Grafana uses for template variables, e.g. `${var:raw}`. So for instance `$timeFrom` is epoch-millis, while `${timeFrom:ISO8601}` would be ISO, etc. Much harder to implement of course, although maybe there's something in the Grafana libraries we can leverage.

**Comment by retrodaredevil** [comment]
I definitely like the idea of using the standard way of substituting that Grafana has with stuff like `templateSrv.replace`. I think there's a way to make it so you can do stuff like `[[variable_name]]` instead of `$variable_name` if you wanted to. 

Maybe instead of using a regex to replace the necessary fields, we could use a more standard way. More info here: https://grafana.com/docs/grafana/latest/reference/templating/

I don't think this is too difficult and I don't think it would break any existing queries if we stopped using regex.

**Comment by retzkek** [comment]
Rather embarrassingly I've just been informed by @marcusolsson that there's [global variables for the dashboard time range in epoch-millis](https://grafana.com/docs/grafana/latest/variables/global-variables/#from-and-to) since 6.0, so we should definitely promote using those, and work with core Grafana to support other formats instead of trying to invent our own.

**Comment by retrodaredevil** [comment]
So could this issue be renamed to something like "Use standard template variables for everything", since we eventually should stop using regex to replace stuff and use Grafana's way.

Or this issue could be closed and we create a new issue.

**Comment by retzkek** [comment]
I've updated the README. I'm going to leave this issue open since it's pretty important for this datasource, probably moreso than for others.  I found an issue [requesting time range variables in seconds](https://github.com/grafana/grafana/issues/18763), I'll chime in there to request ISO8601 (and others) as well.

> since we eventually should stop using regex to replace stuff and use Grafana's way.

I've opened #18 for that.

**Comment by retzkek** [comment]
Good news everyone, this was added in 7.1.2: https://github.com/grafana/grafana/pull/26466
https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__from-and-__to
