### ISSUE TITLE
Support Custom Time Path and Format

### ISSUE THREAD

**Issue by calebsmac** [fifemon/graphql-datasource#16]
Time may not always be at the root of the return in the data path. For example:
![image](https://user-images.githubusercontent.com/26824617/80996265-82e53580-8e0d-11ea-8175-89d2066a013f.png)

In this case, data path is `data.edges`.

Even with aliasing as Time, it is not recognized because it returns `node.Time` rather than Time.

There are two solutions here that I see immediately:

1. A configurable path for time similar to Group By and Data Path
2. Consider any field which *ends in* `.Time` to be the time field. Not sure if this would create too much ambiguity...

Happy to take this on myself though it will probably be quite slow :) Mostly just wanted to highlight this as a potential future feature.

**Comment by retrodaredevil** [comment]
I like the idea of auto detecting the time field. We don't really need another configurable path for time. I think it should first have "Time" take priority, then if there's no "Time" field, it can look for "*.Time".

Auto detecting it should be pretty simple and shouldn't break any existing queries unless someone is querying a Time field when they don't want to . (I think it's valid for a query to not have a Time field. I don't know what those queries are used for, though)

If you want to try and do this yourself, go for it. Of course, it's always up to @retzkek if he'll merge it in. It seems good to me, though.

**Comment by retzkek** [comment]
I'm leaning towards the configurable time field option. It's straightforward to implement and support, and avoids the myriad edge-cases that I can see emerging if we tried to detect the time field.

**Comment by michaelneale** [comment]
auto detecting: https://github.com/fifemon/graphql-datasource/pull/25

it does require some assumptions yes.

**Comment by retzkek** [comment]
As mentioned in #42 there should also be an option to specify timestamp format.

**Comment by retzkek** [comment]
I've added configuration options for time path and format. If anyone wants to test before I release:

```
grafana-cli --pluginUrl https://github.com/retzkek/graphql-datasource/archive/custom-time.zip plugins install fifemon-graphql-datasource
```
