### ISSUE TITLE
Remove grafana-7.0 branch

### ISSUE THREAD

**Issue by retrodaredevil** [fifemon/graphql-datasource#23]
Since the grafana-7.0 branch is 1 commit behind master, does that mean we're going to use master for the grafana 7.0 code? If so, can we delete grafana-7.0 to avoid any confusion?

Or we could make grafana-7.0 the default and stop using master altogether.

**Comment by retzkek** [comment]
Yeah I thought it made more sense to have 7 on master and back-port things as needed to a 6 branch. Branch `grafana-7.0` deleted.
