### ISSUE TITLE
Trying to add auth headers from grafana doesn't work

### ISSUE THREAD

**Issue by mblhaunted** [fifemon/graphql-datasource#3]
It doesn't add an area to include headers, like the other options. It's just a `;` on the page, no form.

**Comment by retzkek** [comment]
First, note that this is using the standard (albiet "alpha") Grafana `DataSourceHTTPSettings` (https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx) React component, so if there's a bug it's there (except the stray semicolon, that's my fault).
That said, I'm not exactly sure what option you're referring to @mblhaunted . Do you mean the "With credentials" option? If so, I believe the intent of that just means that cookies and auth headers from the user's request will be passed through to the datasource. I haven't personally used it, and I found this issue that makes me wonder if it actually works for headers (https://github.com/grafana/grafana/issues/15396).  
So ultimately you're asking for a *new* option to add custom headers from the datasource configuration, is that right? Sounds reasonable to me, but it is something that would need to be added in the standard library for all datasources to use.

**Comment by john3gan** [comment]
This appears to be supported as of grafana 6.7 https://github.com/grafana/grafana/pull/17846

**Comment by retzkek** [comment]
Thanks @john3gan, I've verified that header options are available now with Grafana 6.7.x.
