### ISSUE TITLE
Support data path in Global Variable query

### ISSUE THREAD

**Issue by ggranberry** [fifemon/graphql-datasource#35]
Currently when trying to assign a result from a Graphql Datasource into a Global Variable, there is no option to specify a data path leading to an inability to assign any values

<img width="1146" alt="Screen Shot 2020-11-09 at 5 23 06 PM" src="https://user-images.githubusercontent.com/5805744/98603759-a4d5de00-22b0-11eb-8e60-f7d0c0be51bb.png">

**Comment by ggranberry** [comment]
I can tackle this PR if you want to assign it to me.

**Comment by retzkek** [comment]
Thanks for opening this issue, to be honest I haven't looked into what it would take to support using the datasource for query variables. Historically this has been rather disconnected from the datasource, with a unique editor, query language, etc. I see there's now some [documentation on supporting query variables](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/#add-support-for-query-variables-to-your-data-source), looks pretty straightforward.

**Comment by retzkek** [comment]
@ggranberry absolutely, let me know if you run into any issues. The main challenge I see is that we need to ensure that we get an array of simple values out, rather than objects.

**Comment by ggranberry** [comment]
@retzkek How would you recommend implementing `metricFindQuery`? I was thinking of just calling `query` and then parsing the output

**Comment by retzkek** [comment]
@ggranberry Good question... my first instinct is to use `createQuery()` and `getDocs()` directly, since there's a lot of extra stuff that `query()` handles (multiple targets, time fields, grouping, aliases) that shouldn't apply in this context.

**Comment by ggranberry** [comment]
Hey just getting back to this and I was wondering if you had any documentation on how to build/test this? I was just going to try to install it into a local grafana docker image to test it out. Do I need to do anything besides copy this dir to the plugins folder?

**Comment by retzkek** [comment]
Yep that's all there is to it, or you can set the Grafana plugins directory, e.g. if I have the repo at `/Users/kretzke/fifemon/graphql-datasource`:

```
/usr/local/bin/grafana-server --homepath /usr/local/share/grafana cfg:default.paths.plugins=/Users/kretzke/fifemon
```

Or with Docker:

```
docker run -it --rm -v /Users/kretzke/fifemon:/var/lib/grafana/plugins -p 3000:3000 grafana/grafana
```

Note that you need to restart Grafana anytime you've changed the plugin (after running `yarn dev`).

**Comment by ggranberry** [comment]
PR is up whenever you have time to review 👍
