### ISSUE TITLE
Feature request: support for arithmetic operations on query results

### ISSUE THREAD

**Issue by gcotone** [fifemon/graphql-datasource#36]
Most datasources in Grafana (e.g. prometheus, influxdb, etc) support performing basic arithmetic operation on the query results.
It would be nice to have the same functionality for this plugin.

E.g. use case: Query return bits/minute or packets/minute, which ideally should be normalized to bits/sec or packets/sec respectively.

Current transformation on Grafana are very limited and don't work when you have dynamic grouping.

**Comment by retzkek** [comment]
Thanks for the suggestion @gcotone , but I have a major issue with that: the operations you mention for other datasources are features of the datasource itself, not the Grafana plugin. Generally I'd suggest you should implement such operations/derivations in your GraphQL API, or look at collecting and exporting metrics to an external timeseries database for more complicated use cases.

**Comment by gcotone** [comment]
Hi @retzkek , I understand. Thanks for taking the time to look into this.
