### ISSUE TITLE
Dynamically changing output keys (Group by)

### ISSUE THREAD

**Issue by retrodaredevil** [fifemon/graphql-datasource#4]
Right now I'm testing out GraphQL with Grafana and I'm trying to figure out how to do things similar to how they're done with InfluxDB since I'm already using many InfluxDB queries.

In InfluxDB, we can change the field name to something like this (alias by): `[[tag_identifier]] [[col]]`. You can also group by the identifier so that the data is correctly split up if the identifier is different.

So here's what I'm working with:
```
query {
    data:submissions(from:"$timeFrom", to:"$timeTo"){
        Time:submitTime
        running 
        identifier
    }
}
```
Let's say this will give me a result pretty similar to this:
```
[
   {submitTime: 1234, running: 1234, identifier: "server-1"},
   {submitTime: 1234, running: 300, identifier: "server-2"},
   {submitTime: 5000, running: 400, identifier: "server-1"},
   {submitTime: 5000, running: 500, identifier: "server-2"},
]
```
Right now with the current query it would group server-1 and server-2 into the same field called "running". In this case, my end goal would be to have two separate fields for server-1 and server-2 and have the name of each field be "Server ID: [[tag_identifier]]".

From what I understand this datasource isn't setup to work like this. Do you know if there's something I can do in GraphQL to achieve my desired result? Also, if I were to make a PR for something like this, do you have a recommendation for how I should go about implementing this?

**Comment by retrodaredevil** [comment]
After doing some research, it looks like my goal is very similar to the goal explained here: https://stackoverflow.com/questions/52562555/is-there-a-way-to-group-queries-in-graphql?rq=1

It doesn't look like there's a way to do what I'm trying to do with GraphQL alone. I believe that there would have to be some data manipulation on this datasource's end.

**Comment by retzkek** [comment]
So if I understand correctly, you'd like to have series like this:
```
[
   {submitTime: 1234, server-1: 1234, server-2: 3000},
   {submitTime: 5000, server-1: 400, server-2: 5000},
]
```
[as you pointed out] this isn't really possible with GraphQL, since it's premised on the results matching the request. If you know the server names you could do it, depending on the API. For example if the schema was:
```graphql
type Query {
      submissions(from: String, to: String): [Submission]!
}
type Submission {
    submitTime: String!
    running(identifier: String): Int!
}
```
you could call it like this to get the output you want:
```
query {
    data:submissions(from:"$timeFrom", to:"$timeTo"){
        Time:submitTime
        server-1:running(identifier:"server-1") 
        server-2:running(identifier:"server-2") 
    }
}
```
This of course is not ideal since you have to hardcode in the server names. So yeah it would probably need to be done in the datasource. I don't think it would be terribly difficult to implement, but it would take some thought, especially on how to configure it.

**Comment by retrodaredevil** [comment]
> So if I understand correctly, you'd like to have series like this:

Yep, that's exactly what I want.

> This of course is not ideal since you have to hardcode in the server names.

Yeah, hardcoding things in queries definitely isn't ideal for me.

I just forked the repo about 15 minutes ago and I'm implementing a "Group by" and "Alias by" configuration. I'll have to see how well this works and if I need to change anything.
