### ISSUE TITLE
Multi-value template variable not properly interpolated for repeated panels

### ISSUE THREAD

**Issue by svet-b** [fifemon/graphql-datasource#40]
When panel repetition is enabled for a given template variable, the GraphQL query in each of the repeated panels is executed for _all_ values of the template variable, rather than for the individual value in the specific panel.

For example, let's say we have a Grafana template variable called `asset_id` with multiple values `1, 2, 3`. We also have a panel that's set to repeat for each value of `asset_id`. If in that panel we have the GraphQL query
```
query {
    Assets (where: { 
        id: $asset_id
      }) {
        name            
    }
}
```
then in principle the query in each panel should substitute each of the values of `asset_id`, with queries like `id: 1`, `id: 2`, `id: 3`. This is handled correctly for other datasources I've tried.

Instead, in each panel the query states `id: 1,2,3`, so the same (multi-value) result appears in each of the repeated panels.

I've reviewed some of the other issues/PRs relating to template variables, but I feel like this is separate. Happy to provide additional details if helpful!

**Comment by jazerda** [comment]
+1

**Comment by retzkek** [comment]
Thanks for the report, I can confirm this behavior and agree it's not right. I'd expect Grafana should be handling what values go to each panel, so we're probably (still) using `TemplateSrv` wrong. https://github.com/fifemon/graphql-datasource/blob/master/src/DataSource.ts#L78

**Comment by retzkek** [comment]
Aha! But we make two calls to `replace()`, the first (that handles the legacy range variables) does not pass `scopedVars`: https://github.com/fifemon/graphql-datasource/blob/master/src/DataSource.ts#L73

Easy fix, I'll turn that into one call. PR shortly.
