### ISSUE TITLE
Unix timestamp support?

### ISSUE THREAD

**Issue by copercini** [fifemon/graphql-datasource#42]
Hello!

I have a GraphQL server that sends time data in seconds Unix timestamp, for example `1611252694` that can be translated as `01/21/2021 @ 6:11pm (UTC)`.  Using `Time: timestamp` it simply says that this timestamp is NaN. 

Usually Grafana requires Unix timestamps in milliseconds, so [people do a hack multiplying it by 1000](https://github.com/grafana/grafana/issues/6297), like `SELECT timestamp*1000 as "time"`, is it possible to do in graphql-datasource ? Or is there another way to use this timestamp as Time source?

**Comment by retzkek** [comment]
Unfortunately at the moment that's not possible, we rely on [moment.js string parsing](https://momentjs.com/docs/#/parsing/string/) for timestamps. We definitely should support optionally specifying a [format](https://momentjs.com/docs/#/parsing/string-format/). I've modified #16 to include format since they'd be good to do together.

**Comment by copercini** [comment]
Thanks for your answer! Based in your tips, I was able to make a workaround to support Unix timestamp by changing this line https://github.com/fifemon/graphql-datasource/blob/db9175c393ed132458f391c293912074a4e86c79/src/DataSource.ts#L164 from 
`doc.Time = dateTime(doc.Time);`
to
`doc.Time = dateTime(doc.Time, "X");` 
where `X` is this format in moment https://momentjs.com/docs/#/parsing/string-format/

**Comment by retzkek** [comment]
Great, glad you got it to work for you. If you feel like playing around with the code some more and adding an option to the query form I'd be happy to accept a pull request! ;)

I'm going to close this, since I've combined the issue into #16.

**Comment by copercini** [comment]
I'll try, but my Typescript knowledge is almost zero :grimacing:
