### ISSUE TITLE
How to plot graph panel as a series?

### ISSUE THREAD

**Issue by magaton** [fifemon/graphql-datasource#44]
Hello, 1st day with your plugin and grafana so much changed since the time I last touched it.
I am playing with the Business Review demo app from grandstack.io. 

I have the following response
<img width="1299" alt="Screenshot 2021-02-17 at 14 37 49" src="https://user-images.githubusercontent.com/4103157/108213426-4c27a400-712f-11eb-9ca7-7eab64a30b49.png">

I would like to display counts as bars in graph panel, using stars (3, 4 or 5) as the key.
It works for Table but not for Graph.
What could be the problem?
Thanks!
Milan

**Comment by retzkek** [comment]
AFAIK it's not possible, the graph panel is really still focused on time-series data, but it has some limited support for bucketed histograms - try playing with the x-axis settings and/or transforms. You may have better luck asking in the Grafana Slack or [message board](https://community.grafana.com/).

![image](https://user-images.githubusercontent.com/1627510/108231196-21c1f080-7107-11eb-9760-cd60330afbf2.png)

**Comment by magaton** [comment]
Thanks, clear.
Bar Gauge is definitely a better option since it does not require time.
Now it works as expected.
<img width="1680" alt="Screenshot 2021-02-17 at 22 02 41" src="https://user-images.githubusercontent.com/4103157/108267844-00472000-716c-11eb-8542-acc5b997d4b4.png">
