### ISSUE TITLE
Support for key/value Query Variables

### ISSUE THREAD

**Issue by tijimathew-iot** [fifemon/graphql-datasource#46]
**Is your feature request related to a problem? Please describe.**
I need a workaround while waiting for the graphQL endpoints being developed by the application development team. To this effect, I would like to choose the fields from the graphQL query that I want to use as text for display and value to be passed when used as template variables in dashboards and panel queries.

**Describe the solution you'd like**
I would like to extract the text and value fields similar to postgres data source functionality described here. https://grafana.com/docs/grafana/latest/datasources/postgres/#query-variable

**Describe alternatives you've considered**
Tried to leverage the regex label option to tag the result as text and value but have only succeeded with a single value field. When I used a query with multiple fields, I get every field flattened out as a single column.

Without using regex the result would appear as shown below.
![image](https://user-images.githubusercontent.com/73661376/110476459-fe5be700-80af-11eb-96fe-22a0356d1864.png)

Solution using regex. 
![image](https://user-images.githubusercontent.com/73661376/110476108-9f966d80-80af-11eb-8bfd-5ba535654df3.png)

**Additional context**
Similar to data path, Group by and alias, if there was a way to map the return element against text and value for variables would be useful for the problem we are trying to solve.

**Comment by retzkek** [comment]
I wasn't aware of key/value variables, we'll have to look at how that's implemented in other datasources like postgres.

**Comment by retzkek** [comment]
Ah, so this is a really new feature it seems. Also really easy to implement, I've [pushed a change](https://github.com/retzkek/graphql-datasource/tree/key-value-vars) that implements it like the postgres example, where if the results include both a `__text` and `__value` field (you do this in your GraphQL query like `__text:name`) then it uses them, otherwise it appends all the values like before.

```diff
-      for (const fieldName in doc) {
-        metricFindValues.push({ text: doc[fieldName] });
+      if ('__text' in doc && '__value' in doc) {
+        metricFindValues.push({ text: doc['__text'], value: doc['__value'] });
+      } else {
+        for (const fieldName in doc) {
+          metricFindValues.push({ text: doc[fieldName] });
+        }
```

![image](https://user-images.githubusercontent.com/1627510/110505565-e1c9aa00-80c3-11eb-85bb-10e5471fb151.png)

If this looks good I'll merge and release v1.2.1 soon. If you want to test you can directly use my fork:

```
grafana-cli --pluginUrl https://github.com/retzkek/graphql-datasource/archive/key-value-vars.zip plugins install fifemon-graphql-datasource
```

**Comment by tijimathew-iot** [comment]
I am going to try this out and get back to you.

**Comment by tijimathew-iot** [comment]
I tested with the following scenarios

Multiple __text values for a single __value field: Not a valid use case for this feature but just sharing observed behavior. 
![image](https://user-images.githubusercontent.com/73661376/110577582-eed0b280-8130-11eb-8381-e1433f900fe8.png)

The feature is expected to have 1 to 1 relationship between __text and __value and thus would expect to return the __text values as the values displayed in the drop down but __value returned as variable value.

![image](https://user-images.githubusercontent.com/73661376/110577727-3bb48900-8131-11eb-8769-744913e260c5.png)

Example of variables working 
![image](https://user-images.githubusercontent.com/73661376/110578133-18d6a480-8132-11eb-9b04-07c38b5f030b.png)

**Comment by retzkek** [comment]
@tijimathew-iot thanks for testing! I'll get this documented and get a release out this week.

**Comment by tijimathew-iot** [comment]
@retzkek When is the next release scheduled? wanted to use this feature if possible.

**Comment by retzkek** [comment]
@tijimathew-iot sorry, I wanted to get another long-desired feature into this release. [v1.3.0 released](https://github.com/fifemon/graphql-datasource/releases/tag/v1.3.0), and I've [opened a PR](https://github.com/grafana/grafana-plugin-repository/pull/899) to update the plugin repository.

**Comment by tijimathew-iot** [comment]
I appreciate it. I see that the changes will get merged into the grafana repo when they approve your PR. Thank you so much for the quickest turnaround in my industry experience!

**Comment by retzkek** [comment]
You're welcome. Sometimes it can take a while for Grafana to update the plugin repository (hence why I wanted to get another feature or two in), although the plugin checker has streamlined that process a bit.

> Thank you so much for the quickest turnaround in my industry experience!

Small projects can move quickly sometimes, you caught me on a good day 😄

**Comment by lucas-bremond** [comment]
@retzkek This is an awesome feature!
I am unable to make this work when dealing with Relay data:

```gql
query {
  groups {
    edges {
      node {
        __value: id
        __text: name
      }
    }
  }
}
```

I've tried with the following data paths:

- `groups`
- `groups.edges`
- `groups.edges.node`
- `groups.edges.*.node`

Is there any secret approach? :)
