### ISSUE TITLE
Timestamp format moment

### ISSUE THREAD

**Issue by spillz-dxb** [fifemon/graphql-datasource#55]
I am using the Wiki example Deutsche Bahn Arrivals , and am getting the response .However i am unable to get the time stamp formatted and use the time series panel .Here is the screen shot below . Am i missing something ?.

![image](https://user-images.githubusercontent.com/5900390/117177351-fc798000-ade1-11eb-922b-4d72574c9703.png)

Any Help is appreciated 

Thanks in advance

**Comment by retzkek** [comment]
Try leaving the time format blank, it can handle most "standard" formats.

![image](https://user-images.githubusercontent.com/1627510/117179697-0034e480-ad99-11eb-921a-c5bd8d8a3433.png)

**Comment by spillz-dxb** [comment]
Hi Retzkek,
Thanks this works , but im unable to get it to the graph , the table works fine as yours .

![image](https://user-images.githubusercontent.com/5900390/117240163-4f365480-ae41-11eb-9d3a-92b880787ae7.png)

Is there something im missing ?.
Thanks again

**Comment by retzkek** [comment]
The query isn't returning numeric data, so Grafana can't graph it. You could force it to convert a field to a number with a Transform:

![image](https://user-images.githubusercontent.com/1627510/117323220-50bd4800-ae54-11eb-80ae-ea209066596a.png)

If you're just playing around to learn how to use it, I'd suggest using the new [test datasource](https://github.com/fifemon/graphql-test-source) and [dashboard](https://grafana.com/grafana/dashboards/14079) instead.
