### ISSUE TITLE
Strf time to human readable format

### ISSUE THREAD

**Issue by MittaDhanunjaya** [fifemon/graphql-datasource#69]
Hello I have a metric which is giving me a value 20210913220124. How can I convert this by using Grafana? FYI I am using Prometheus as a datasource. Is it possible to convert the timestamp to 2021:09:12 and 22:01:24???

Thanks in advance,
Dhanunjaya Mitta

**Comment by retzkek** [comment]
@MittaDhanunjaya you should ask that question in the [Grafana Forums](https://community.grafana.com/).
