### ISSUE TITLE
Should the first 'data' in the data path be optional?

### ISSUE THREAD

**Issue by retrodaredevil** [fifemon/graphql-datasource#7]
Right now when specifying a data path, you always use `data.<something>`. Take this query:

```
query {
    data:submissions(user:"$user", from:"$timeFrom", to:"$timeTo"){
        Time:submitTime
        idle running completed
    }
}
```
The data path is `data.data`. Obviously the second data makes sense, but does the first "data" ever change? Unless there's a reason that I'm unaware of, making the data path just `data` for the above query makes more sense.

If you agree with this, we could probably phase out the first "data" in the data path and make it optional. This could prove to be difficult (for instance does "data.data" become "data.data.data" internally or just stay as "data.data"). But a data path like "submissions" could be internally converted to "data.submissions".

Also, I plan to submit a PR later for multiple data paths in the same query. I probably won't change this in that PR.

**Comment by retzkek** [comment]
That's a good question, that I've gone back and forth on. The GraphQL response will always have the top-level "data" to correspond to the "query" level in the request. But then "query" is optional and often omitted, so making "data" optional probably makes the most sense, so long as we can reliably determine when to add it.

Side note: that example should probably be updated to remove the `data:` label, it's a holdover from the earliest version where the data path was hard-coded to `data.data`, and now is just confusing as you pointed out. I'd actually like to re-write all the examples to use public APIs so users have something concrete to learn with, like the [Deutsche Bahn example I included in the plugin repo PR](https://github.com/grafana/grafana-plugin-repository/pull/602). Need to find an API that has numerical timeseries data. I'll open a new issue for that.

**Comment by retrodaredevil** [comment]
The simplest solution might be to try to get data from the `getDocs()` method, then if it fails, try `getDocs()` again but instead pass `"data." + dataPath` to see if it works or try it the other way around first. If both fail, then just throw the first error.

The only reason you might want to have the data path not start with `data.***`, is if you wanted to query for errors for some reason. Then the data path could be `errors`, and uh, you could display errors as annotations maybe.

My vote would be to just break backwards compatibility before the first version is released. I can make a PR that does this without any other changes if you want, but I don't want to do it if you aren't on board.

**Comment by retzkek** [comment]
Sounds good to me, thanks!
