### ISSUE TITLE
Data being returned but not displayed

### ISSUE THREAD

**Issue by Dilbarjot** [fifemon/graphql-datasource#78]
The data is being returned in the data block, but somehow not being displayed. The dashboard shows no data. 

![graphql_error_nodata](https://user-images.githubusercontent.com/46788967/157115853-7e5c2385-d02a-4ed8-b333-894e845db4ea.PNG)

**Comment by retzkek** [comment]
Expand the response items, check the timestamps and the timepicker settings. Verify that the time field is set correctly.

**Comment by Dilbarjot** [comment]
Is timestamp required? This is not time-series data.

**Comment by retzkek** [comment]
No, it does not, but you didn't give me much to go off so I'm starting with the "make sure it's plugged in and turned on" items. :)

Check that the data path is correct, it should be `[censored].items` where `[censored]` is what you have blacked out.

**Comment by Dilbarjot** [comment]
Yes, Sorry, i will provide more details.
![extended_graphql](https://user-images.githubusercontent.com/46788967/157293339-f280ad66-fbcc-424e-ab7b-16db96ff4e16.PNG)

And each item in an array is an object. Having structure as 
```python
{
  name: "john"
  age: 24
}
```

**Comment by retzkek** [comment]
That should work fine. Can you post the panel query/configuration please?

**Comment by Dilbarjot** [comment]
![graphql_query](https://user-images.githubusercontent.com/46788967/157295467-b9b17b9f-2905-4834-af1c-cef5a30e06e5.PNG)

**Comment by Dilbarjot** [comment]
This may also help.

![graphql_stat](https://user-images.githubusercontent.com/46788967/157295942-b44db27b-1f8e-464c-b053-e86b87b42bd8.PNG)
![graphql_data](https://user-images.githubusercontent.com/46788967/157295948-323100e3-2a0c-468a-8497-21c791eadc38.PNG)

**Comment by retzkek** [comment]
You need to set "Data path", in this case to `demoQuery.items`.

**Comment by Dilbarjot** [comment]
Ahh, I feel stupid. It is working now. Thanks a lot.
